replicaCount: 1
namespace: paata
image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: "nginx"

keda:
  enabled: true
  pollingInterval: 30 
  cooldownPeriod: 60 
  minReplicaCount: 1
  maxReplicaCount: 6 